jupyterhub:
  hub:
    config:
      Authenticator:
        admin_users:
          - 7c76d04b-2a80-4db1-b985-a2d2fa2f708c
          - 09056164-42f5-4113-9fd7-dd852e63ff1d
          - adb7ebad-9fb8-481a-bc2c-6c0a8b6de670
  proxy:
    https:
      enabled: true
      letsencrypt:
        contactEmail: yuvipanda@gmail.com
  singleuser:
    workingDir: /home/jovyan
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "homes/{username}"
    memory:
      guarantee: 512M
      limit: 2G
